### ISSUE TITLE
Invariant Violation: Element type is invalid

### ISSUE THREAD

**Issue by dkuida** [Hacker0x01/react-datepicker#1333]
### Expected behavior
When I test with enzyme using shallow render - I should be able to .find('DatePicker') 
but it returns 0 results. - trying with mount() throws an error

```
	Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

and that error is on the mount itself before I even try to find it
### Steps to reprodcue
the components under test
```tsx
<div className='l-flex l-flex-c t-field t-field-pad'>
                <label>
                    LMP
                </label>
                <i className='t-sep'/>
                <span className='t-validation-wrap l-fg1'>
                     <DatePicker
                         locale={'he-IL'}
                         className='t-field-text w100 t-field--date'
                         selected={this.state.selectedDate ? moment(this.state.selectedDate) : null}
                         onChange={this._setDate}
                     />
                </span>
            </div>
```

**Comment by tomaskallup** [comment]
👍 Also having this problem.

Here's a reproduction test code:
```jsx
import * as React from 'react';
import {configure, mount} from 'enzyme';
import Adapter from 'enzyme-adapter-react-16';
import DatePicker from 'react-datepicker';

configure({ adapter: new Adapter});

describe('DatePicker component', () => {

    describe('render', () => {
        test('without crashing', () => {
            const onChange = jest.fn(),
                props = {
                    onChange
                };

            const snap = mount(<DatePicker {...props} />);

            expect(snap).toMatchSnapshot();
        });
    });
});
```

I managed to fix it by editing the module code in node_modules:
`react-datepicker/lib/index.js`
I added a default export.
```js
module.exports = DatePicker;
module.exports.default = DatePicker;
```

This issue is most likely related to how babel handles importing modules.

**Comment by tomaskallup** [comment]
After some more digging around, the problem seems to be this:
```js
Object.defineProperty(exports, "__esModule", {
  value: true
});
```

Babel add this piece of code which allows it to handle importing of transpiled modules. I'll try to solve this and create PR when I have the time.

**Comment by carlostxm** [comment]
Changing import to `const DatePicker = require('react-datepicker');` worked for me and I can launch tests using jest + enzyme. 

However, with this change the application cannot launch and now I'm getting this error in the console:
<pre>
React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
</pre>

**Comment by EmergentBehavior** [comment]
Also running into same exact error as @carlostxm

**Comment by mattnedrich** [comment]
I had this issue. Wasn't able to root cause it precisely, but was able to workaround it by setting the `dropdownMode` prop to `"select"`

🤷‍♂️

**Comment by kensplanet** [comment]
> Changing import to `const DatePicker = require('react-datepicker');` worked for me and I can launch tests using jest + enzyme.
> 
> However, with this change the application cannot launch and now I'm getting this error in the console:
> 
> React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.

I am having the same issue.

**Comment by hodzanassredin** [comment]
> 
> 
> > Changing import to `const DatePicker = require('react-datepicker');` worked for me and I can launch tests using jest + enzyme.
> > However, with this change the application cannot launch and now I'm getting this error in the console:
> > React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
> 
> I am having the same issue.

+1

**Comment by dwilhel1** [comment]
Thanks to a coworker pointing this thread out, the `expected a string (for built-in components) or a class/function (for composite components) but got: object` error we had was resolved with the following:

**Old**
```
<DatePicker />
```

**New**
```
<DatePicker.default />
```

**Comment by devn** [comment]
+1

**Comment by dwilhel1** [comment]
It's me, back again. I ran into this issue again with the same codebase after updating our bundler (Rollup) and its plugins.

We're planning to switch to a Material UI datepicker, but for now I've done the following:

1. Revert `<DatePicker.default />` to `<DatePicker />`
2. Mock the `react-datepicker` import in the Jest unit tests:

```javascript
jest.mock('react-datepicker', () => {
    const React = require('react');
    return class DatePicker extends React.Component {
        render() {
            return <div id="DatePicker" />;
        }
    };
});
```

**Comment by radoslawgrochowski** [comment]
For anyone still experiencing problem and having trouble with reexporting this in both cjs and esm - you might try this:
```tsx
import * as RDP from 'react-datepicker'

const RDPC = (((RDP.default as any).default as any) ||
  (RDP.default as any) ||
  (RDP as any)) as typeof RDP.default

/* ...  */

<RDPC />
```

**Comment by ziyadshaikh013** [comment]
> For anyone still experiencing problem and having trouble with reexporting this in both cjs and esm - you might try this:
> 
> ```tsx
> import * as RDP from 'react-datepicker'
> 
> const RDPC = (((RDP.default as any).default as any) ||
>   (RDP.default as any) ||
>   (RDP as any)) as typeof RDP.default
> 
> /* ...  */
> 
> <RDPC />
> ```

This worked like a charm, but could you also mention why it happened. I have a custom datepicker component in one of my library, it depends on react-datepicker, I am bundling library using vite and added 'react-datepicker' to external.

When I import this component in a next.js project I get the error, but adding your above code, fixed the issue

**Comment by certifiedbice** [comment]
The .default property is used to access the default export of a module when the module is imported as a namespace object. For example, if you import a library like react-datepicker using import * as DatePicker from 'react-datepicker', the default export of the library becomes accessible through DatePicker.default.

This behavior typically occurs because:

1. The library uses a default export, but the project imports it as a namespace object, wrapping the default export inside a default property.
2. There are quirks with bundling tools or compatibility issues between CommonJS and ES Modules, which can cause the default export to be nested within a default property.

If you encounter this issue, you can resolve it by either:

1. Importing the library directly using import DatePicker from 'react-datepicker', which accesses the default export directly.
2. If the above doesn’t work due to bundling issues, using DatePicker.default ensures you're explicitly accessing the correct export.

This happens because some tools wrap the module exports differently based on configuration or how the library was compiled, especially when mixing ES Modules and CommonJS. Using .default is a fallback to access the default export when a direct import does not work.

To Further elaborate:

**What Does .default Mean?**

In JavaScript ES Modules, when a library uses a default export, it is accessed through the default property when imported as a namespace (or as a single object).

For example:

A library like react-datepicker may export its default component as follows:

`// react-datepicker.js
export default DatePicker;
`
If you import the entire module (not destructured), the default export will be accessed via the .default property:

`import * as DatePicker from 'react-datepicker';

// Access the default export
const Component = DatePicker.default;
`
This is different from using a direct import statement for a default export:

`import DatePicker from 'react-datepicker';

// Directly accesses the default export
<DatePicker />
`

**Why Does .default Work Here?**

If the react-datepicker library is improperly imported or bundled, it might return an object instead of the default export directly. This happens because:

1. Namespace Import: If react-datepicker is imported like import * as DatePicker, the default property contains the default exported component.
3. Compatibility Issues: Some bundlers (like older versions of Webpack or custom configurations) may wrap the module's default export in an object with a default property.

**Why Didn’t <DatePicker /> Work Directly?**

This issue likely occurred due to a mismatch in how the library was exported and how your project imported it. Here are potential causes:

1. Improper Import: If you used import * as DatePicker, it treats the entire module as an object, requiring .default to access the default export.
3. ESM and CommonJS Interoperability: If react-datepicker was compiled in a way that mixes CommonJS and ES Modules, it may wrap the default export under the default property when imported into an ES Module project.

**How to Resolve This?**

Correct Import Style:

Try importing react-datepicker directly using its default export:

`import DatePicker from 'react-datepicker';
`
If that works, it’s the cleaner and recommended approach.
Fallback:

If the above doesn’t work due to library or environment quirks, you can safely use:

`import * as DatePicker from 'react-datepicker';

// Usage
<DatePicker.default {...props} />
`

Or even:

`import DatePicker from 'react-datepicker';

// Usage
<DatePicker.default {...props} />
`

This ensures you’re accessing the correct default export.

**Key Takeaways:**

1. .default is used to access the default export when the module is imported as a namespace.
2. The need for .default often arises from how the library is exported or bundled.
4. Prefer direct imports (import DatePicker from 'react-datepicker') if the library supports it.

**Comment by teknosains** [comment]
> The .default property is used to access the default export of a module when the module is imported as a namespace object. For example, if you import a library like react-datepicker using import * as DatePicker from 'react-datepicker', the default export of the library becomes accessible through DatePicker.default.
> 
> This behavior typically occurs because:
> 
> 1. The library uses a default export, but the project imports it as a namespace object, wrapping the default export inside a default property.
> 2. There are quirks with bundling tools or compatibility issues between CommonJS and ES Modules, which can cause the default export to be nested within a default property.
> 
> If you encounter this issue, you can resolve it by either:
> 
> 1. Importing the library directly using import DatePicker from 'react-datepicker', which accesses the default export directly.
> 2. If the above doesn’t work due to bundling issues, using DatePicker.default ensures you're explicitly accessing the correct export.
> 
> This happens because some tools wrap the module exports differently based on configuration or how the library was compiled, especially when mixing ES Modules and CommonJS. Using .default is a fallback to access the default export when a direct import does not work.
> 
> To Further elaborate:
> 
> **What Does .default Mean?**
> 
> In JavaScript ES Modules, when a library uses a default export, it is accessed through the default property when imported as a namespace (or as a single object).
> 
> For example:
> 
> A library like react-datepicker may export its default component as follows:
> 
> ```
> export default DatePicker;
> ```
> 
> If you import the entire module (not destructured), the default export will be accessed via the .default property:
> 
> ```
> import * as DatePicker from 'react-datepicker';
> // Access the default export
> const Component = DatePicker.default;
> ```
> 
> This is different from using a direct import statement for a default export:
> 
> ```
> import DatePicker from 'react-datepicker';
> // Directly accesses the default export
> <DatePicker />
> ```
> 
> **Why Does .default Work Here?**
> 
> If the react-datepicker library is improperly imported or bundled, it might return an object instead of the default export directly. This happens because:
> 
> 1. Namespace Import: If react-datepicker is imported like import * as DatePicker, the default property contains the default exported component.
> 2. Compatibility Issues: Some bundlers (like older versions of Webpack or custom configurations) may wrap the module's default export in an object with a default property.
> 
> **Why Didn’t Work Directly?**
> 
> This issue likely occurred due to a mismatch in how the library was exported and how your project imported it. Here are potential causes:
> 
> 1. Improper Import: If you used import * as DatePicker, it treats the entire module as an object, requiring .default to access the default export.
> 2. ESM and CommonJS Interoperability: If react-datepicker was compiled in a way that mixes CommonJS and ES Modules, it may wrap the default export under the default property when imported into an ES Module project.
> 
> **How to Resolve This?**
> 
> Correct Import Style:
> 
> Try importing react-datepicker directly using its default export:
> 
> ```
> import DatePicker from 'react-datepicker';
> ```
> 
> If that works, it’s the cleaner and recommended approach. Fallback:
> 
> If the above doesn’t work due to library or environment quirks, you can safely use:
> 
> ```
> import * as DatePicker from 'react-datepicker';
> // Usage
> <DatePicker.default {...props} />
> ```
> 
> Or even:
> 
> ```
> import DatePicker from 'react-datepicker';
> // Usage
> <DatePicker.default {...props} />
> ```
> 
> This ensures you’re accessing the correct default export.
> 
> **Key Takeaways:**
> 
> 1. .default is used to access the default export when the module is imported as a namespace.
> 2. The need for .default often arises from how the library is exported or bundled.
> 3. Prefer direct imports (import DatePicker from 'react-datepicker') if the library supports it.

none of this works in my side. im using Remix (vite). my implementation

```jxs
import * as DatePicker from 'react-datepicker';

<DatePicker.default
      id="order_date"
      dateFormat="dd/MM/yyyy"
      name="order_date"
      onChange={handleChangeDate}
      selected={order_date}
    />
```

**Comment by teknosains** [comment]
Got this issue. 

Here's my work around using @radoslawgrochowski's workaround

wrap it in a component

```jsx
import * as RDP from 'react-datepicker';
import "react-datepicker/dist/react-datepicker.css";

// this is a workaround for react-datepicker issue
// https://github.com/Hacker0x01/react-datepicker/issues/1333#issuecomment-1251934708

const DatePickerBase = (((RDP.default as any).default as any) ||
  (RDP.default as any) ||
  (RDP as any)) as typeof RDP.default

export const DatePicker = (props: any) => {

  return (
    <DatePickerBase 
      {...props}
      showIcon
    />
  );
};
```

use it like
```jsx
import { DatePicker } from "~/components/DatePicker";

// ...

<DatePicker
    name="order_date"
    selected={order_date}
    onChange={handleChangeDate}
    dateFormat="dd-MM-yyyy"
  />

```

**Comment by Trentsquaw** [comment]
Focus on this https://stackdev.space/questions/the-specified-type-is-incorrect-anticipated-a-string-for-standard-components-or-a-classfunction-for-combined-components-but-received-undefined-within-react-native answer
