### ISSUE TITLE
IE10 freeze

### ISSUE THREAD

**Issue by aferrandi** [Hacker0x01/react-datepicker#141]
If I run the example:

http://cdn.rawgit.com/Hacker0x01/react-datepicker/master/example/index.html

the 3rd line (the one with no date already selected) makes internet explorer 11 freeze when I try to choose a date in the datepicker.
Firefox and Chrome don't have any problem.

**Comment by sconno05** [comment]
I ran into this with IE 9 and 10 as well.  It looks like it was introduced with v0.11 (I was not able to reproduce with v0.10).  I verified that this was not caused by my pull request #135.  I would appreciate a fix ASAP, I've been waiting on v0.11.

**Comment by RSO** [comment]
I will check it out, however, as of yet I have no way to test in IE, I'll have to look into that as well.

**Comment by RSO** [comment]
I'll have to download an IE11 vm for my mac, so that'll take some time. If somebody else could provide me with a trace/screenshot/whatever it would mean a lot to me!

**Comment by sconno05** [comment]
There are no errors being console logged as far as I can see.  I am attaching a screenshot, the steps to reproduce are:

1. Open IE
2. Go to http://cdn.rawgit.com/Hacker0x01/react-datepicker/master/example/index.html
3. Click the first input field
4. Select a date
5. IE locks up, must be shut down

![image](https://cloud.githubusercontent.com/assets/2985457/8942377/4542d3c4-3532-11e5-819b-c4f8dfc07bc5.png)

**Comment by RSO** [comment]
Fixed in dad57db772c492b9446e78da183f6a7984e6f1a5. @martijnrusschen will do a release. Thanks for reporting!

**Comment by RSO** [comment]
Now I'll have to figure out how to run tests in sauce-labs, and write a test for this in IE!

**Comment by martijnrusschen** [comment]
Version 0.11.2 has been released!

**Comment by sconno05** [comment]
Thanks for the quick turn around guys.

**Comment by sconno05** [comment]
I am unfortunately still seeing this issue in IE10.  IE9 seems to be working.  I was able to reproduce after upgrading locally and on the examples page.

**Comment by martijnrusschen** [comment]
Debugging here #150, would be cool if we could reproduce these issues in a test.

**Comment by sconno05** [comment]
It looks like this is still not working in IE10 as of 0.11.3. I unfortunately will not be able to debug until sometime next week but I would really appreciate a fix.

**Comment by truckingsim** [comment]
This freezes in IE11 and IE10 in 0.11.4.  We've been attempting to debug it but haven't gotten anywhere with it yet.

**Comment by sconno05** [comment]
It looks like IE is handling the input's onChange event in an unexpected way, which is causing an infinite loop when you select a value from the calendar.  I made a modification that will fix this.  I am not sure if it is the best fix.  I cannot initiate a pull request though because I needed to add a hack to our version to fix another IE issue, which is preventing the calendar from closing when you press enter.

See changes made to fix the IE freeze issue:
https://github.com/Hacker0x01/react-datepicker/compare/master...ShipCompliant:66389ec2811168b22bf1d14ba4e2f48fa73393ca

**Comment by martijnrusschen** [comment]
Thanks for looking into this, I'll see if I can create a PR based on your changes. Would be happy to get this fixed though!

**Comment by dcousineau** [comment]
@martijnrusschen @sconno05 try my PR above and let me know if that works for you both (it's working for us)

**Comment by martijnrusschen** [comment]
@sconno05 Can you confirm, that PR fixed your issues too? I'm happy to merge it if it fixes the IE issues. Thanks @dcousineau!

**Comment by dcousineau** [comment]
No problem!

![](http://media0.giphy.com/media/wTzPSxZBqSove/giphy.gif)

**Comment by sconno05** [comment]
I pointed our app to https://github.com/croscon/react-datepicker.git, but
the infinite loop was still occurring in IE10.

**Comment by martijnrusschen** [comment]
To make sure, did you point it to the correct branch? Looking at his repo, it should be `bugfix-ie-infinite-loop`

**Comment by sconno05** [comment]
Good call.  Pointing to the correct branch, it does fix our issue.

**Comment by martijnrusschen** [comment]
Cool, lets do this! Thanks for confirming the fix @sconno05

**Comment by martijnrusschen** [comment]
Released: https://github.com/Hacker0x01/react-datepicker/releases/tag/v0.11.5

**Comment by dcousineau** [comment]
![](http://www.lukeshavak.com/wp-content/uploads/2012/04/Homer-Simpson-Woohoo.gif)

**Comment by martijnrusschen** [comment]
Resolving this, lets reopen if it still occurs! Thanks guys!
