### ISSUE TITLE
minDate & maxDate don't work with Month Picker

### ISSUE THREAD

**Issue by nonconformatevi** [Hacker0x01/react-datepicker#1685]
I have this DatePicker component:

`<DatePicker
        selected={new Date()}
	onChange={date => {this.changeFiltersDates(date, type)}}
	dateFormat="MM/yyyy"
	showMonthYearPicker
	className="private-date-filter"
	name="from"
        calendarClassName="date-filter-calendar"
        placeholderText="From"
	minDate={this.defaultMinDate}
	maxDate={this.defaultMaxDate} />`

where 

`this.defaultMinDate = new Date(2017, 0, 1);
 this.defaultMaxDate = new Date();
`
but DatePicker  component dont't work correctly, because don't respect the minDate and maxDate props.

minDate allows the selection of an extra year back and maxDate allows the selection of one more year ahead.

**Comment by gautam-relayr** [comment]
Hi @nonconformatevi Thanks for reporting this bug. If I understand the use case correctly, you want the user to select only those months which are in between the defaultMinDate and defaultMaxDate, which is in your case is between **Jan 01 2017** and **present**

**Comment by nonconformatevi** [comment]
Hi @gautam-relayr, yes you understand correctly!
Thanks for your help.

**Comment by gautam-relayr** [comment]
@nonconformatevi It's fixed with the PR(https://github.com/Hacker0x01/react-datepicker/pull/1692) which got merged recently. Please wait for the next release.

**Comment by nonconformatevi** [comment]
Thanks very much @gautam-relayr!

**Comment by gautam-pahuja** [comment]
@nonconformatevi Can you please close this issue if it's no longer valid.

**Comment by FadyGuirguis** [comment]
I downloaded the package from npm today and the issue is still there. Is it released yet?

**Comment by sree96** [comment]
Even I am facing the same Issue

**Comment by owlblinked** [comment]
same issue

**Comment by fazzaMmsApis** [comment]
yes...same issue for me...maxDate is not working with monthYear Picker.
<DatePicker
            selected={props.selected}
            isClearable={true}
            onChange={props.onChange}
            maxDate={new Date()}
            className="form-control"
            // dateFormat="MM/yyyy"
            showMonthYearPicker
            placeholderText={props.placeholder}
          />

**Comment by dataffinityhealth** [comment]
@gautam-pahuja  Any status update on this? Are you still maintaining the package?

**Comment by sonalk215** [comment]
Hi, I am using react-datepicker as follows:

        <DatePicker
             selected={this.props.selectedDate}
             onChange={this.props.changeEndTime}
             showTimeSelect
              showTimeSelectOnly
              timeIntervals={30}
              timeCaption="Time"
              className={classes.timer}
              dateFormat="h:mm aa"
              minTime={setHours(setMinutes(new Date(), 0), 17)}
              maxTime={setHours(setMinutes(new Date(), 30), 20)}    
          />

But, all the times in the dropdown are shown as disabled.  I tried from the site itself and it works there, but in my code it is not working
Please help
