### ISSUE TITLE
Props being inferred as any since v7

### ISSUE THREAD

**Issue by cascornelissen** [Hacker0x01/react-datepicker#5042]
**Describe the bug**
A number of props are inferred as `any` after updating `react-datepicker` to v7. This makes it impossible to extend the `DatePicker` component's props for a component that renders a `DatePicker`.

**To Reproduce**
Install react-datepicker v7 (7.3.0 at the moment of writing) and let TypeScript infer types for props that are not directly configured in the `DatePickerProps` interface.

```ts
import React from 'react';
import DatePicker, { DatePickerProps } from 'react-datepicker';

// These get inferred as `any`
type A = React.ComponentProps<typeof DatePicker>['minDate'];
type B = DatePickerProps['maxDate'];
type C = DatePickerProps['dateFormatCalendar'];

// These work
type D = DatePickerProps['open'];
```

**Expected behavior**
The type is correctly inferred.

**Screenshots**
<img width="643" alt="image" src="https://github.com/user-attachments/assets/8bc34716-b38d-4cc5-96d1-7fbf90552405">
<img width="654" alt="image" src="https://github.com/user-attachments/assets/05b202ae-5e11-44f3-bf2d-3276d2501246">

**Additional context**
TypeScript 5.5.4

**Comment by floriancargoet** [comment]
I have the same issue. 
I believe it's because the portal.d.ts is missing. This introduces an `any` in the types which breaks `DatePickerProps`.
When building react-datepicker myself, `portal.d.ts` is generated (and fixes my project if I copy it to my `node_modules/react-datepicker/dist`). I don't know why it's missing from the NPM package.

**Comment by floriancargoet** [comment]
It looks like it was reported here: https://github.com/Hacker0x01/react-datepicker/issues/5129
And it was fixed 2 days ago: https://github.com/Hacker0x01/react-datepicker/commit/1b13e38a2a857da1e36f9fc81142107e6d8fab5f

**Comment by Christoffer-M** [comment]
Is there a temporary way to fix this until the a new version with the fix is released? This is causing build errors, so cant release.

**Comment by floriancargoet** [comment]
@Christoffer-M in my project, locally, I copy in `node_modules/react-datepicker/dist` the `portal.d.ts` I got by cloning & building react-datepicker. 
For an automated build, I'm thinking of using https://www.npmjs.com/package/patch-package while waiting for a release.

**Comment by martijnrusschen** [comment]
Try https://github.com/Hacker0x01/react-datepicker/releases/tag/v7.5.0

**Comment by lucassantoskiavi** [comment]
Hello!
I am facing this issue even with v7.5.0

**Comment by lucassantoskiavi** [comment]
I am still facing this issue with version 7.5.0. 
import { DatePickerProps } from 'react-datepicker'; is being inferred as any

**Comment by lucassantoskiavi** [comment]
Just found the issue
I updated @types/react and it fixed. At some point between @types/react  18.0.1 and 18.3.12 this (`type PropsWithChildren<P> = P & { children?: ReactNode | undefined };`) changed to this (`type PropsWithChildren<P = unknown> = P & { children?: ReactNode | undefined };`). And the older version cause that CalendarProps be inferred as any because React.PropsWithChildren is being inferred as any. Maybe we should check where this definition changed and post as peerDependency.
